image: node:8.9

options:
  max-time: 10

pipelines:
  default:
    - step:
        script:
          - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
          - npm install
          - npm run lint
          - npm run coverage
